
@echo off

REM !!! Generated by the fmp-cli 1.88.0.  DO NOT EDIT!

md ProcessInvoker\Assets\3rd\fmp-xtc-processinvoker

cd ..\vs2022
dotnet build -c Release

copy fmp-xtc-processinvoker-lib-mvcs\bin\Release\netstandard2.1\*.dll ..\unity2021\ProcessInvoker\Assets\3rd\fmp-xtc-processinvoker\
